name: Lembretes WhatsApp

on:
  push:
    branches:
      - Lembrete
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  lembretes_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Dependências
        run: pip install -r requirements.txt

      - name: Definir Variáveis de Ambiente
        run: |
          echo "ACCOUNT_SID=${{ secrets.ACCOUNT_SID }}" >> $GITHUB_ENV
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "TELEFONE=${{ secrets.TELEFONE }}" >> $GITHUB_ENV
        shell: bash

      - name: Verificar Variáveis (Debug)
        run: |
          echo "Verificando variáveis de ambiente..."
          echo "ACCOUNT_SID=$ACCOUNT_SID"
          echo "AUTH_TOKEN=$AUTH_TOKEN"
          echo "TELEFONE=$TELEFONE"
          env | grep ACCOUNT_SID
          env | grep AUTH_TOKEN
          env | grep TELEFONE
          if [ -z "$ACCOUNT_SID" ]; then echo "[ERRO] Variável ACCOUNT_SID está vazia!"; fi
          if [ -z "$AUTH_TOKEN" ]; then echo "[ERRO] Variável AUTH_TOKEN está vazia!"; fi
          if [ -z "$TELEFONE" ]; then echo "[ERRO] Variável TELEFONE está vazia!"; fi

      - name: Rodar Script de Lembretes
        run: |
          python src/lembretes.py
