name: Lembretes WhatsApp

on:
  push:
    branches:
      - Lembrete
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  lembretes_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Dependências
        run: pip install -r requirements.txt

      - name: Definir Variáveis de Ambiente
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TELEFONE: ${{ secrets.TELEFONE }}
        run: |
          echo "export ACCOUNT_SID=${{ secrets.ACCOUNT_SID }}" >> $GITHUB_ENV
          echo "export AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "export TELEFONE=${{ secrets.TELEFONE }}" >> $GITHUB
